version: '3.8'

services:
  mongo-primary:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: mongo-primary
    ports:
      - "27027:27017"
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  mongo-secondary-1:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: mongo-secondary-1
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  mongo-secondary-2:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: mongo-secondary-2
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  mongo-secondary-3:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: mongo-secondary-3
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  mongo-hidden:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: mongo-hidden
    ports:
      - "27021:27017"
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all

  setup-replica-set:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: setup-replica-set
    depends_on:
      - mongo-primary
      - mongo-secondary-1
      - mongo-secondary-2
      - mongo-secondary-3
      - mongo-hidden
    networks:
      - mongo-cluster
    command: >
      bash -c "
        echo 'Waiting for MongoDB nodes to start...' &&
        sleep 30 &&
        mongosh --host mongo-primary:27017 --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo-primary:27017\" },
              { _id: 1, host: \"mongo-secondary-1:27017\" },
              { _id: 2, host: \"mongo-secondary-2:27017\" },
              { _id: 3, host: \"mongo-secondary-3:27017\" },
              { _id: 4, host: \"mongo-hidden:27017\", hidden: true, priority: 0 }
            ]
          });
          rs.status();
        '
      "

networks:
  mongo-cluster:
    driver: bridge